source_channel_names:
- mCherry EX561 EM600-37
- GFP EX488 EM525-45
target_channel_name: Phase3D
affine_transform_zyx:
- - 0.9907113909721375
  - 0.01176353357732296
  - -0.0023756297305226326
  - 11.669376373291016
- - -0.0027884417213499546
  - -0.022817790508270264
  - -1.2758545875549316
  - 1199.9306640625
- - -0.015202872455120087
  - 1.2757678031921387
  - -0.022782862186431885
  - -5.484277725219727
- - 0.0
  - 0.0
  - 0.0
  - 1.0
keep_overhang: false
interpolation: linear
time_indices: all
verbose: false
